{{- if .Values.eachservice.enabled }}
  {{- $fullName := include "cp-zookeeper.fullname" . }}
  {{- $zkServers := .Values.servers | int }}
  {{- $servicePort := .Values.eachservice.servicePort }}
  {{- $root := . }}
  {{- range $i, $e := until $zkServers }}
    {{- $responsiblePod := printf "%s-%d" (printf "%s" $fullName) $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-zookeeper.fullname" $root }}-{{ $i }}-svc
  labels:
    app: {{ include "cp-zookeeper.name" $root }}
    chart: {{ template "cp-zookeeper.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    pod: {{ $responsiblePod }}
spec:
  ports:
    - name: {{ $responsiblePod }}-svc
      port: {{ $servicePort }}
      targetPort: {{ $servicePort }}
  clusterIP: None
  selector:
    app: {{ include "cp-zookeeper.name" $root }}
    release: {{ $root.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $responsiblePod | quote }}
  {{- end }}
{{- end }}
